### ISSUE TITLE
Day1 Todo

### ISSUE THREAD

**Issue by yu-uj** [codestates/BEB-05-HALPME#3]
## TODO
- [x]  팀명 정하기
- [x]  프로젝트 기획
- [x]  기능 및 시나리오 작성
- [x]  Flow Chart
- [x]  포지션 정하기
- [x]  각 포지션 Todo List 작성
- [x] DB ERD 작성
- [ ]  참고할 레퍼런스 찾아오기
- [x]  git team repo issue, discussion, wiki, project 등 작성

## Estimated time

> Pick one
`3h`

## Labels
- Estimated time: `E: 3h`
- Group : `FE`, `BE`
- Sprint: `Setup`
- Urgency: `High`
