### ISSUE TITLE
Day2 Todo

### ISSUE THREAD

**Issue by yu-uj** [codestates/BEB-05-HALPME#4]
## TODO

- [x]  개발 일정 & 테스크 정리
- [x]  git repo 및 file tree 정리
- [x]  개발 환경 세팅
- [ ]  이슈 정리
- [x]  개발 시작

## Estimated time

> Pick one

`6h`

## Labels
- Estimated time: `E: 6h`
- Group : `FE`, `BE`
- Sprint: `Setup`, `Sprint1`
- Urgency: `Middle`
